/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DAO;
import entidades.Produtos;
import entidades.Usuario;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author eharv
 */
public class TelaCadastros extends javax.swing.JFrame {

    DAO dao = new DAO();
    

    /**
     * Creates new form TelaCadastros
     */
    public TelaCadastros() {
        initComponents();
        
        URL iconURL = getClass().getResource("/img/chef16.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpLogo = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();
        jlChefClick = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jlNomeCompleto = new javax.swing.JLabel();
        jlNomeUsuario = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jlConfirmeSenha = new javax.swing.JLabel();
        jtfNomeCompleto = new javax.swing.JTextField();
        jtfNomeUsuario = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jpfConfSenha = new javax.swing.JPasswordField();
        jbCadastrarUser = new javax.swing.JButton();
        jbListarUser = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlNomeProduto = new javax.swing.JLabel();
        jlValorProduto = new javax.swing.JLabel();
        jtfNomeProduto = new javax.swing.JTextField();
        jlQuantidade = new javax.swing.JLabel();
        jtfQuantidade = new javax.swing.JTextField();
        jtfValorProduto = new javax.swing.JTextField();
        jbCadastrarProduto = new javax.swing.JButton();
        jbListarProdutos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastros");
        setBackground(new java.awt.Color(255, 255, 255));

        jpLogo.setBackground(new java.awt.Color(255, 255, 255));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chef128.png"))); // NOI18N

        jlChefClick.setFont(new java.awt.Font("Segoe Script", 1, 48)); // NOI18N
        jlChefClick.setText("ChefClick");

        javax.swing.GroupLayout jpLogoLayout = new javax.swing.GroupLayout(jpLogo);
        jpLogo.setLayout(jpLogoLayout);
        jpLogoLayout.setHorizontalGroup(
            jpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpLogoLayout.createSequentialGroup()
                    .addGap(229, 229, 229)
                    .addComponent(jlChefClick)
                    .addContainerGap(83, Short.MAX_VALUE)))
        );
        jpLogoLayout.setVerticalGroup(
            jpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlLogo)
                .addContainerGap())
            .addGroup(jpLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpLogoLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jlChefClick)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlNomeCompleto.setText("Nome Completo do Funcionário");

        jlNomeUsuario.setText("Nome de Usuário");

        jlSenha.setText("Senha");

        jlConfirmeSenha.setText("Confirme a senha");

        jtfNomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeCompletoActionPerformed(evt);
            }
        });

        jpfConfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfConfSenhaActionPerformed(evt);
            }
        });
        jpfConfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfConfSenhaKeyPressed(evt);
            }
        });

        jbCadastrarUser.setText("Cadastrar");
        jbCadastrarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarUserActionPerformed(evt);
            }
        });

        jbListarUser.setText("Listar");
        jbListarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNomeCompleto)
                    .addComponent(jlNomeUsuario)
                    .addComponent(jlSenha)
                    .addComponent(jlConfirmeSenha)
                    .addComponent(jtfNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jbListarUser)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbCadastrarUser))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jpfConfSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpfSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNomeUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlNomeCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlNomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlConfirmeSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpfConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrarUser)
                    .addComponent(jbListarUser))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro de Usuários", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jlNomeProduto.setText("Nome do Produto");

        jlValorProduto.setText("Valor (Por unidade)");

        jlQuantidade.setText("Quantidade");

        jtfValorProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfValorProdutoActionPerformed(evt);
            }
        });
        jtfValorProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfValorProdutoKeyPressed(evt);
            }
        });

        jbCadastrarProduto.setText("Cadastrar");
        jbCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarProdutoActionPerformed(evt);
            }
        });
        jbCadastrarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarProdutoKeyPressed(evt);
            }
        });

        jbListarProdutos.setText("Listar");
        jbListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarProdutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlValorProduto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtfValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jbListarProdutos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCadastrarProduto))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlNomeProduto)
                                .addComponent(jtfNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlQuantidade)
                            .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(144, 144, 144))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeProduto)
                    .addComponent(jlQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jlValorProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrarProduto)
                    .addComponent(jbListarProdutos))
                .addGap(112, 112, 112))
        );

        jTabbedPane1.addTab("Cadastro de Produtos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeCompletoActionPerformed

    private void jpfConfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfConfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfConfSenhaActionPerformed

    private void jbCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarProdutoActionPerformed
        // TODO add your handling code here:
        Produtos p = new Produtos();
        p.setNomeProduto(jtfNomeProduto.getText());
        p.setValorProduto(Double.parseDouble(jtfValorProduto.getText()));
        p.setQuantidadeProduto(Integer.parseInt(jtfQuantidade.getText()));
        dao.salvar(p);

        jtfNomeProduto.setText("");
        jtfValorProduto.setText("");
        jtfQuantidade.setText("");

    }//GEN-LAST:event_jbCadastrarProdutoActionPerformed

    private void jbCadastrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarUserActionPerformed
        // TODO add your handling code here:

        Usuario user = new Usuario();

        user.setNomeCompletoFunc(jtfNomeCompleto.getText());
        user.setNomeUsuario(jtfNomeUsuario.getText());
        //ValueOf transforma char[] em String
        user.setSenhaUsuario(String.valueOf(jpfSenha.getPassword()));
        dao.salvar(user);

        jtfNomeCompleto.setText("");
        jtfNomeUsuario.setText("");
        jpfSenha.setText("");
        jpfConfSenha.setText("");


    }//GEN-LAST:event_jbCadastrarUserActionPerformed

    private void jpfConfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfConfSenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Usuario user = new Usuario();

            user.setNomeCompletoFunc(jtfNomeCompleto.getText());
            user.setNomeUsuario(jtfNomeUsuario.getText());
            //ValueOf transforma char[] em String
            user.setSenhaUsuario(String.valueOf(jpfSenha.getPassword()));
            dao.salvar(user);

            jtfNomeCompleto.setText("");
            jtfNomeUsuario.setText("");
            jpfSenha.setText("");
            jpfConfSenha.setText("");
        }
    }//GEN-LAST:event_jpfConfSenhaKeyPressed

    private void jbCadastrarProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarProdutoKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jbCadastrarProdutoKeyPressed

    private void jtfValorProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfValorProdutoActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_jtfValorProdutoActionPerformed

    private void jtfValorProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorProdutoKeyPressed
        // TODO add your handling code here:
          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Produtos p = new Produtos();
            p.setNomeProduto(jtfNomeProduto.getText());
            p.setValorProduto(Double.parseDouble(jtfValorProduto.getText()));
            p.setQuantidadeProduto(Integer.parseInt(jtfQuantidade.getText()));
            dao.salvar(p);

            jtfNomeProduto.setText("");
            jtfValorProduto.setText("");
            jtfQuantidade.setText("");
          }
    }//GEN-LAST:event_jtfValorProdutoKeyPressed

    private void jbListarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarUserActionPerformed
        // TODO add your handling code here:
        ListaUsuarios lu = new ListaUsuarios();
        
        lu.setVisible(true);
        
    }//GEN-LAST:event_jbListarUserActionPerformed

    private void jbListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarProdutosActionPerformed
        // TODO add your handling code here:
        ListaProdutos lp = new ListaProdutos();
        
        lp.setVisible(true);
    }//GEN-LAST:event_jbListarProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbCadastrarProduto;
    private javax.swing.JButton jbCadastrarUser;
    private javax.swing.JButton jbListarProdutos;
    private javax.swing.JButton jbListarUser;
    private javax.swing.JLabel jlChefClick;
    private javax.swing.JLabel jlConfirmeSenha;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlNomeCompleto;
    private javax.swing.JLabel jlNomeProduto;
    private javax.swing.JLabel jlNomeUsuario;
    private javax.swing.JLabel jlQuantidade;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlValorProduto;
    private javax.swing.JPanel jpLogo;
    private javax.swing.JPasswordField jpfConfSenha;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfNomeCompleto;
    private javax.swing.JTextField jtfNomeProduto;
    private javax.swing.JTextField jtfNomeUsuario;
    private javax.swing.JTextField jtfQuantidade;
    private javax.swing.JTextField jtfValorProduto;
    // End of variables declaration//GEN-END:variables
}
